### PR TITLE
CORE-1184: add the missing wrapper around messages delivered to the DE UI via AMQP.

### PR DESCRIPTION
**Pull request by slr71**

### CODE REVIEW

**Review by ash3rz — APPROVED** [review]
I didn't catch anything 👍

**Review by ianmcorvidae — APPROVED** [review]
Looks reasonable to me! The only thing I can think of is if there's any way to combine this query with another one to remove a database roundtrip, but I also haven't spotted anything like that, so :shipit: if you want!

**Comment by slr71** [comment]
Thanks for the reviews!

**Comment by slr71** [comment]
Yeah, this just does a database insert and an update before obtaining the count. There's not really any existing query that I could modify to obtain the count here. I suppose I could save a round trip by combining the insert and the update, but I kept them separate so that I could allow the database to generate the notification ID (and include the ID in the outgoing message).

**Comment by slr71** [comment]
Merging this now.

**Pull request merged**
